---
# Datagen Source Connector - Pageviews
# Managed via GitOps - changes to this file deploy automatically via ArgoCD
# BRANCH: main - Standard pageviews data generation
apiVersion: platform.confluent.io/v1beta1
kind: Connector
metadata:
  name: datagen-gitops-demo
  namespace: confluent
spec:
  class: io.confluent.kafka.connect.datagen.DatagenConnector
  taskMax: 1
  connectClusterRef:
    name: connect
  configs:
    # Topic to write data to
    kafka.topic: "gitops-pageviews"
    quickstart: "pageviews"
    
    # Converters
    key.converter: "org.apache.kafka.connect.storage.StringConverter"
    value.converter: "io.confluent.connect.avro.AvroConverter"
    value.converter.schema.registry.url: "http://schemaregistry.confluent.svc.cluster.local:8081"
    
    # Data generation settings
    max.interval: "1000"
    iterations: "10000000"
